### ISSUE TITLE
`IdMaker.cs` - ID i `set` metod na njemu

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleItalianRestaurant#2]
Pricali smo o *set*-ovanju ID-eva, odnosno da to ne moze.

S druge strane, zasto *singleton* ima ID? Pa ID mu mora biti 1, zar ne... Ili 0, sta god. Dakle, nemoj automatski zuvati stvari u klase, razmisli da li treba ili ne, ocigledno ovde ne bas.

**Comment by NikolaDmitrasinovic** [comment]
Znam, ali zato je private. Moram da pogledam nesto na temu "best practices" da bih ovo resio kako treba.

**Comment by NikolaVetnic** [comment]
Prosto nemoj stavljati suvisne stvari, to je sve. Kad bi imao bazu, da li bi singleton-a cuvao u bazi? Onda mu ne treba ID...
