### ISSUE TITLE
`Items` paket/direktorijum

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleItalianRestaurant#3]
Ovakvi paketi se obicno zovu `utils` ili nesto slicno.

Ok, u sustini `IdMaker` klasa i `IItem` interfejs nisu bas dobar spoj... ID jeste deo svakog itema i jeste nesto sto `IdMaker` proizvodi, ali nisu semanticki povezani niti su strukturalno slicni... Mozda si `IdMaker` mogao u neki `utils` paket van svega, pa da mu napravis mozda i vise brojaca (jedan za pica, jedan za hranu, **ali ne mora**) jer tako mozes da ga visestruko koristis... Ne moras se mozda zamarati sada time, samo hocu da kazem da je to prilicno siroka tema kao sto vidis.

**Comment by NikolaDmitrasinovic** [comment]
IdMaker nije bio deo prvobitnog plana vec sam ga uveo na samom kraju iz nuzde. On u sustini daje id koji se koristi iskljucivo da obelezi na neki nacin proizvod na meniju posto preko njega posle formiram racun. Zato nema poseban za pice i hranu. Znam da nije idealno, ali nisam znao sta da radim. Ocigledno, nisam znao ni gde da ga stavim, mogao je tu biti paket pod nazivom utils.

**Comment by NikolaVetnic** [comment]
Nije problem, nije ni toliko lose resenje da imas jedan ID generator za sve. Definitivno `utils` paket doduse, tu uvek ide nesto sto ne spada nigde drugde.
