### ISSUE TITLE
`IItem` interfejs i `Drink` klasa koja ga nasledjuje imaju ista polja

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleItalianRestaurant#4]
Ja sad ne poznajem C#, mozda je to neki fazon? U Javi clanovima (poljima, atributima) nadklase pristupas sa `super` recimo, iz `Drink` bi pristupio `Id`-u koji se nalazi u interfejsu sa `super.id`, ali takodje bi bio i prosto vidljiv kao da je clan te klase (sto i jeste). Odvojena tema je da li interfejsi treba da sadrze polja jer **interfejsi nisu klase**. To je jos jedna malo sira tema.

**Comment by NikolaDmitrasinovic** [comment]
To bi isto tako moglo i ovde kada recimo IItems ne bio bio interfejs nego apstraktna klasa. Ovako to i nisu prava polja, ali to sad i nije bitno. Sustina je da je cela ta konstrukcija poprilicno nesrecno izvedena sa moje strane. Hteo sam na neki nacin sve da objedinim, ali nisam izgleda izabrao dobar put.

**Comment by NikolaVetnic** [comment]
Dobro, treba malo iskustva za to. U sustini zapamti ovo kao primer, dakle interfejs bi bio bolja opcija sa metodom `getPrice()` jer bi onda negde to mogao da bude prosto getter koji vraca vrednost polja, a negde bi mogao da radi nesto "pametnije".
