### ISSUE TITLE
Katastrofalno imenovanje

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleItalianRestaurant#5]
Ovo nikad ne smes:
```C#
    IdMaker id = IdMaker.Instance;
    Id = id.GetId();
```

Znaci, tebi se varijable razlikuju samo po tome sto je jedno `Id` a drugo `id`, to je bukvalno trazenje nevolje 😄 Druga stvar, tebi taj `IdMaker` ne treba na vise mesta vec samo jednom tako da je tacan odgovor:
```C#
    Id = IdMaker.Instance.GetId();
```

**Comment by NikolaDmitrasinovic** [comment]
Facepalm sto bi nas narod rekao... 
Popravicu.

**Comment by NikolaVetnic** [comment]
Da, jbg, nzm kakve su konvencije u C#, ja sam metode u C# nazivao u PascalCase-u, a varijable u camelCase-u... Osim za konstante, to je all caps SNAKE_CASE.
