### ISSUE TITLE
Da li ovo radi kako treba?

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleItalianRestaurant#6]
Pazi ovo, klasa `Juice`:
```C#
    public Juice(string name, double price, double volume) : base(name, price, volume)
    {
    }
```

Nzm kako radi C#, ali u Javi ti mozes u podklasi ili klasi koja impl neki interfejs da ostavis tako "prazan" `ctor`, tada ona poziva automatski `super()` sto je `ctor` nadklase, ili ako nema toga poziva `ctor` klase `Object` koja je praroditelj svih klasa u Javi... Medjutim, ako `super()` prima neke parametre oni nece biti automatski prosledjeni. Da li C# to radi automatski? Da li mozda ti treba da uradis nesto tipa `super(name, price, volume)` ? Ili ti to radi ovaj `base` dodatak?

To sve inace nije toliko bitno, razliciti jezici imaju razlicite olaksice i *streamline* momente, tzv. sintakticki secer 🍬

**Comment by NikolaDmitrasinovic** [comment]
Ovo "base" bi bio sinonim za "super" u Javi, recimo. Radi kao podmazao :)

**Comment by NikolaVetnic** [comment]
E, pa eto... *Syntactic sugar*, sto bi se reklo...
