### ISSUE TITLE
Alternativni nacin da se resi ovo

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleItalianRestaurant#7]
Govorim za pica pre svega ali moguce je da vazi za sve... Ti imas tehnicki tri klase koje nemaju nista posebno u sebi, da ne pricamo o tome da su interno potpuno identicne (`Juice`, `Soda`, `Water`); ako ti ja zadam da dodas jos 50 novih pica, to je pakao, slozices se...

Kako si to mogao drugacije? Mogao si da imas jednu klasu `Drink` (kao sto i imas) i da ona onda ima nekakav identifikator tipa (enum), tada ti je dodavanje novih pica prosto dodavanje novih vrednosti enuma u ovom slucaju...

"E, ali sta ako ja dodam koktele koji ce imati jos i listu sastojaka, onda je ovaj pristup bolji ipak?", cujem pitanje... Ali nije zapravo. Tebi nista ne brani da zapravo nasledis tu klasu sa nekim `Cocktail` i dodas sve sta ti treba jer ce ta klasa i dalje da ima cenu, zapreminu, enum koji odredjuje tip, itd. Najvaznije da ce `Cocktail` klasa i dalje biti takodje i tip `Drink`...

Ne moras menjati ali razmisljaj o tome.

**Comment by NikolaDmitrasinovic** [comment]
Razumem sta hoces da kazes, mislim da necu sada menjati.

**Comment by NikolaVetnic** [comment]
Da, nemoj sad ali sledeci koji budes resavao razmisli da li moze tako - mozda ne moze, nemoj na silu gurati.
